name: Bug Report
description: File a bug report
labels: ["bug", "triage required"]
body:
  - type: markdown
    id: intro-md
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please ensure you provide as much information as possible to help us resolve the issue.
  - type: dropdown
    id: existing-issue
    attributes:
      label: "Verified issue does not already exist?"
      description: "Please search to see if an issue already exists for the bug you encountered."
      options:
        - "No, I did not search"
        - "I have searched and found no existing issue"
    validations:
      required: true
  - type: textarea
    id: errors-received
    attributes:
      label: "What error did you receive?"
      description: "If you received an error, please paste it in full below"
    validations:
      required: true
  - type: textarea
    id: command-run
    attributes:
      label: "Steps to Reproduce"
      description: "What can we do to reproduce the reported error?"
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: "Any other information"
      description: "Please provide any other information that may assist us with this issue."
    validations:
      required: false
  - type: markdown
    id: env-info
    attributes:
      value: "## Environment Details"
  - type: dropdown
    id: host-detail
    attributes:
      label: "What version of SQL Server are you running?"
      multiple: true
      options:
        - SQL Server 2014
        - SQL Server 2016
        - SQL Server 2022
        - SQL Server 2019
        - SQL Server 2022
    validations:
      required: true
  - type: textarea
    id: sql-version
    attributes:
      label: "SQL Server Build number"
      description: "You can provide the output from: SELECT @@VERSION"
    validations:
      required: true