blank_issues_enabled: false
contact_links:

   - name: Ask a question about Sequel Formula or get support
     url: https://github.com/Rich-In-SQL/Sequel-Formula/discussions/new/choose
     about: Get support via chat