name: Data Quality
description: File an issue with our data
labels: ["data quality", "triage required"]
body:
  - type: markdown
    id: intro-md
    attributes:
      value: |
        Thanks for taking the time to fill out this report!
        Please ensure you provide as much information as possible to help us resolve the issue.
  - type: dropdown
    id: existing-issue
    attributes:
      label: "Verified this issue does not already exist?"
      description: "Please search to see if an issue already exists for the issue you have encountered."
      options:
        - "No, I did not search"
        - "I have searched and found no existing issue"
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: "What type of problem have you found?"
      description: "Please select one of the below options to let us know what type of issue you have found."
      options:
        - "Data is missing"
        - "Data is incorrect"
    validations:
      required: true
  - type: textarea
    id: problem-found
    attributes:
      label: "What is missing or needs adding?"
      description: "Please provide as much information on what is wrong or what needs adding"
    validations:
      required: true
  - type: textarea
    id: more-info
    attributes:
      label: "Where can we find more information."
      description: "Where can we find more information on this, is there a link that has the data etc."
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: "Any other information"
      description: "Please provide any other information that may assist us with this issue."
    validations:
      required: false