name: Improvement Request
description: File an improvement request for something to be improved or added.
labels: [improvement, "triage required"]
body:
  - type: markdown
    id: intro-md
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        This request will be reviewed and labelled accordingly.
  - type: textarea
    attributes:
      label: "Summarize Functionality"
      description: "Please provide a clear/concise description of what problem this feature will solve."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Technical Details"
      description: "Provide links to concepts, example code or write-ups of the desired functionality."
    validations:
      required: false